x-logging-default: &default-logging
  options:
    max-size: "20m"
    max-file: "3"
  driver: json-file

x-tagger-env: &tagger-env
  RUST_LOG: INFO,tracing=ERROR,ml_tagger::processors::lemmatize_words=INFO
  ONNX_THREADS: 4
  DATA_DIR: /data
  EMBEDDINGS_FILE: mmap:/data/delfi_cbow.150.fifu
  ONNX_FILE: /data/model.onnx
  LEMMA_URL: http://lemma:8000/analyze/{}
  LEMMA_CACHE: 50000
  EMBEDDINGS_CACHE: 40000
  CACHE_KEY: 01J4HMRM6GAHP6HNE67JRXXKT4

x-tagger-common: &tagger-common
  image: airenas/ml-tagger:${TAGGER_ML_VERSION}
  logging: *default-logging
  restart: unless-stopped
  volumes:
    - tagger-data:/data:ro
  depends_on:
    - tagger-vol
  environment:
    <<: *tagger-env


services:
  lex-1:
    image: semantikadocker.vdu.lt/lex:2021.04.02
    restart: unless-stopped
    logging: *default-logging

  lex-2:
    image: semantikadocker.vdu.lt/lex:2021.04.02
    restart: unless-stopped
    logging: *default-logging

  lex-3:
    image: semantikadocker.vdu.lt/lex:2021.04.02
    restart: unless-stopped
    logging: *default-logging

  lex-4:
    image: semantikadocker.vdu.lt/lex:2021.04.02
    restart: unless-stopped
    logging: *default-logging

  lex-5:
    image: semantikadocker.vdu.lt/lex:2021.04.02
    restart: unless-stopped
    logging: *default-logging

  lex-6:
    image: semantikadocker.vdu.lt/lex:2021.04.02
    restart: unless-stopped
    logging: *default-logging

  tagger-1:
    <<: *tagger-common
    environment:
      <<: *tagger-env
      SEGMENTATION_URL: http://lex-1:8080/
      LEX_URL: http://lex-1:8080/
    ports:
      - "8001:8000"
  tagger-2:
    <<: *tagger-common
    environment:
      <<: *tagger-env
      SEGMENTATION_URL: http://lex-2:8080/
      LEX_URL: http://lex-2:8080/
    ports:
      - "8002:8000"
  tagger-3:
    <<: *tagger-common
    environment:
      <<: *tagger-env
      SEGMENTATION_URL: http://lex-3:8080/
      LEX_URL: http://lex-3:8080/
    ports:
      - "8003:8000"
  tagger-4:
    <<: *tagger-common
    environment:
      <<: *tagger-env
      SEGMENTATION_URL: http://lex-4:8080/
      LEX_URL: http://lex-4:8080/
    ports:
      - "8004:8000"
  tagger-5:
    <<: *tagger-common
    environment:
      <<: *tagger-env
      SEGMENTATION_URL: http://lex-5:8080/
      LEX_URL: http://lex-5:8080/
    ports:
      - "8005:8000"
  tagger-6:
    <<: *tagger-common
    environment:
      <<: *tagger-env
      SEGMENTATION_URL: http://lex-6:8080/
      LEX_URL: http://lex-6:8080/
    ports:
      - "8006:8000"

  lemma:
    image: airenas/lema:${LEMA_SERVICE_VERSION}
    restart: unless-stopped
    logging: *default-logging
    environment:
      - LEMA_HUNSPELL_SKIP_OFFENSIVE=false
      - LEMA_TYPE=hunspell_lema
      - SECRET=${LEMA_SECRET}

volumes:
  tagger-data:
    name: tagger-data
